tailwind.config = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'page-bg': '#F6F3ED',
        'panel-bg': '#EBE7DF',
        'soft-card': '#E3DFD6',
        'soft-card-2': '#F0EBE3',
        text: '#22201C',
        muted: '#7A7368',
        'muted-light': '#B5AFA4',
        line: '#D4CEC3',
        black: '#22201C',
        'deep-black': '#12100E',
        'white-card': '#FDFAF4',
        'white-soft': '#F6F3ED',
        ink: '#22201C',
        'ink-deep': '#12100E',
        'on-ink': '#F6F3ED',
        accent: '#9D6E53',
        'accent-deep': '#7A5540',
        'accent-light': '#C49A7E',
        'accent-soft': 'rgba(157, 110, 83, 0.14)',
        sage: '#6B7F72',
        'sage-deep': '#55665A',
        'sage-muted': '#E6EBE7',
        'sage-soft': 'rgba(107, 127, 114, 0.12)',
        'panel-tint-start': '#E8E4DC',
        'panel-tint-end': '#DDD8CE',
        'card-tint-start': '#F0EBE3',
        'card-tint-end': '#E8EBE7',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        '3xl': '2rem',
        '4xl': '3rem',
      },
      spacing: {
        gutter: '24px',
        unit: '4px',
        sm: '16px',
        md: '32px',
        xl: '128px',
        lg: '64px',
        margin: '40px',
        xs: '8px',
        section: '160px',
      },
      fontFamily: {
        label: ['Inter'],
        'body-lg': ['Inter'],
        display: ['Inter'],
        h2: ['Inter'],
        h1: ['Inter'],
        h3: ['Inter'],
        'body-md': ['Inter'],
      },
      fontSize: {
        label: ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        display: ['82px', { lineHeight: '1.05', letterSpacing: '-0.04em', fontWeight: '700' }],
        h2: ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        h1: ['48px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '700' }],
        h3: ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['15px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
      },
    },
  },
}
